version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - local_db

  local_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=local_dev
      - POSTGRES_PASSWORD=local_dev
      - POSTGRES_DB=local_dev

volumes:
  postgres_data: