# Generated by Django 4.0 on 2023-03-05 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Local', 'Local'), ('National', 'National'), ('Regional', 'Regional'), ('International', 'International')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_no', models.IntegerField()),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('representative_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('member', models.ManyToManyField(to='challenge.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.instance'),
        ),
    ]
